apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-front
        image: neroalfonso/whoami:1.0.0
        ports:
        - containerPort: 80