apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          serviceName: whoami-front
          servicePort: 80
      - path: /api
        pathType: ImplementationSpecific
        backend:
          serviceName: whoami-back
          servicePort: 80